Hospital/Models/PricingPacks.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models
{
    public class PricingPacks
    {
        [Key]
        public int id { get; set; }
        [Required]
        [Display(Name = "Plan Name", Prompt = "Plan name.")]
        public string PlanName { get; set; }
        [Required]
        [Display(Name = "Description", Prompt = "Plan description.")]
        public string Description { get; set; }
        [Required]
        [Display(Name = "Billing Period", Prompt = "Billing Period")]
        [DataType(DataType.Text)]
        public string BillingPeroid { get; set; }
        [DataType(DataType.Currency)]
        [Display(Name = "Amount", Prompt = "Amount")]
        public string Amount { get; set; }
        [Display(Name = "Created Date")]
        public Nullable<DateTime> CreatedDate { get; set; }
        [Display(Name = "Modified Date")]
        public Nullable<DateTime> ModifiedDate { get; set; }
        [Display(Name = "Plan Type")]
        public PlanType PlanType { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        [Display(Name = "Features", Prompt = "Features")]
        public string Features {get; set;}
        public string Features2 { get; set; }
        public string Features3 { get; set; }
        public string Features4 { get; set; }
        public string Features5 { get; set; }
        public string Features6 { get; set; }
        public string Features7 { get; set; }
        public string Features8 { get; set; }
        public string Features9 { get; set; }
        public string Features10 { get; set; }
    }

    public enum PlanType { 
        Free,
        Paid
    }

}

Hospital/Controllers/PricingPacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital.Models;
using Microsoft.AspNetCore.Authorization;
using Hospital.DBServices.SuperAdmin;
using Hospital.Models.CommonModels;

namespace Hospital.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PricingPacksController : Controller
    {
        private readonly HMSContext _context; 
        private readonly ISuperAdmin superAdmin;

        public PricingPacksController(HMSContext context, ISuperAdmin _superAdmin)
        {
            _context = context;
            superAdmin = _superAdmin;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        #region Get all packages list
        [HttpPost]
        public async Task<IActionResult> GetAllPackagesList()
        {
            try
            {
                string draw = Request.Form["draw"];
                string order = Request.Form["order[0][column]"];
                string orderDir = Request.Form["order[0][dir]"];
                int startRec = Convert.ToInt32(Request.Form["start"]);
                int pageSize = Convert.ToInt32(Request.Form["length"]);
                string featurename = Request.Form["columns[0][search][value]"];
                string createddate = Request.Form["columns[2][search][value]"];
                string modifieddate = Request.Form["columns[3][search][value]"];
                string searchTerm = Request.Form["search[value]"];
                IEnumerable<PricingPacks> stateList = await superAdmin.GetAllPackagesList();
                long TotalRecordsCount = stateList.Count();

                #region filters   
                if (!string.IsNullOrEmpty(searchTerm) && !string.IsNullOrWhiteSpace(searchTerm))
                {
                    stateList = stateList.Where(x =>
                        x.PlanName != null && x.PlanName.ToLower().Contains(searchTerm.ToLower()));
                }
                if (!string.IsNullOrEmpty(featurename) && !string.IsNullOrWhiteSpace(featurename))
                {
                    stateList = stateList.Where(x => x.PlanName != null && x.PlanName.ToLower().Contains(featurename.ToLower()));
                }
                #endregion
                long FilteredRecordCount = stateList.Count();

                #region Sorting  


                switch (order)
                {
                    case "0":
                        stateList = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? stateList.OrderByDescending(p => p.PlanName) : stateList.OrderBy(p => p.PlanName);
                        break;
                    default:
                        stateList = stateList.OrderByDescending(p => p.id);
                        break;
                }
                #endregion

                var listfeatures = stateList.Skip(startRec).Take(pageSize).ToList()
                    .Select(d => new PricingPacks()
                    {
                        id = d.id,
                        PlanName = d.PlanName,
                        Description = d.Description,
                        BillingPeroid = d.BillingPeroid,
                        Amount = d.Amount,
                        Features = d.Features,
                        PlanType = d.PlanType,
                        IsActive = d.IsActive,
                        CreatedDate = d.CreatedDate ,
                        ModifiedDate = d.ModifiedDate ,
                    }).ToList();
                return Json(new
                {
                    draw = Convert.ToInt32(draw),
                    recordsTotal = TotalRecordsCount,
                    recordsFiltered = FilteredRecordCount,
                    data = listfeatures
                });
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        #endregion Get all packages list

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var pricingPack = await superAdmin.GetPricingPackById(id);
            if (pricingPack == null)
            {
                return NotFound();
            }
            return View(pricingPack);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        } 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RequestResponse> Create(PricingPacks pricingPack)
        {
            RequestResponse response = new RequestResponse();
            if (ModelState.IsValid)
            {
                response = await superAdmin.CreatePackage(pricingPack);

            }
            else
            {
                response.Status = false;
            }
            return response;
        }
        [HttpPost] 
        public async Task<RequestResponse> Update(PricingPacks pricingPack)
        {
            RequestResponse response = new RequestResponse();
            if (ModelState.IsValid)
            {
                response = await superAdmin.UpdatePackage(pricingPack);
            }
            else
            {
                response.Status = false;
            }
            return response;
        }

        [HttpGet]
        public async Task<IActionResult> EditPackage(int Id)
        { 
            var pricingPack =await superAdmin.GetPricingPackById(Id);
            if (pricingPack == null)
            {
                return NotFound();
            }
            return View(pricingPack);
        } 
         
    }
}

Hospital/Views/PricingPacks/Create.cshtml
@model Hospital.Models.PricingPacks

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}
@section Styles{
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
}

<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Pricing Packages</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 Description">
            <form asp-action="Create" asp-controller="PricingPacks" id="createPackageForm">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            <input type="hidden" asp-for="IsActive" value="false" />
                            <input type="hidden" asp-for="IsDeleted" value="false" />
                            <label asp-for="PlanName" class="control-label"></label>
                            <input type="text" asp-for="PlanName" class="form-control" />
                            <span asp-validation-for="PlanName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <i class="fa fa-asterisk" aria-hidden="true"></i>  <label asp-for="PlanType" class="control-label"></label>
                            <input type="radio" asp-for="PlanType" name="PlanType" value="@PlanType.Free" class="planType" /> Free
                            <input type="radio" asp-for="PlanType" name="PlanType" value="@PlanType.Paid" class="planType" /> Paid
                            <span asp-validation-for="PlanType" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <i class="fa fa-calendar" aria-hidden="true"></i>  <label asp-for="BillingPeroid" class="control-label"></label>
                            @*<input type="text" asp-for="BillingPeroid" class="form-control" />*@
                            <select asp-for="BillingPeroid" class="form-control">
                                <option value="1 month">1 month</option>
                                <option value="2 month">2 month</option>
                                <option value="3 month">3 month</option>
                                <option value="6 month">6 month</option>
                                <option value="1 year">1 year</option>
                            </select>
                            <span asp-validation-for="BillingPeroid" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <i class="fa fa-money" aria-hidden="true"></i>  <label asp-for="Amount" class="control-label"></label>
                            $<input type="number" min="0" asp-for="Amount" class="form-control" />
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <i class="fa fa-file" aria-hidden="true"></i> <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <i class="fa fa-list-alt" aria-hidden="true"></i>
                            <label asp-for="Features" class="control-label">Features (Add features & seperate with comma)</label>
                            <span style="display: flex">
                                <textarea id="featurename" typeof="text" asp-for="Features" class="form-control features_list" placeholder="Add features and seperate with comma"></textarea>
                            </span>
                            <span asp-validation-for="Features" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2 col-xl-2">
                        <button class="btn btn-md btn-primary"
                                id="addBtn" type="button" style="margin-top:30px">
                            Add Feature
                        </button>
                    </div>
                </div>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center col-9">Features</th>
                            <th class="text-center col-3">Remove Feature</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                    </tbody>
                </table>
                <div class="m-t-20 text-center">
                    <button type="submit" class="btn btn-success submit-btn">Create Packages</button>
                </div>
            </form>


        </div>

    </div>
</div>

@section Scripts {



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
    </script>

    <script>
        $(document).ready(function () {

            // Denotes total number of rows
            var Features = new Array(10);
            var rowIdx ;
            var txt = "";
           
            document.getElementById("featurename").innerHTML = txt;

            // jQuery button click event to add a row
            $('#addBtn').on('click', function () {
                for (rowIdx = 0; rowIdx < Features.length; rowIdx++) {
                   
                        // Adding a row inside the tbody.
                        $('#tbody').append(`<tr id="R${++rowIdx}">
                 <td class="row-index text-center">
                 <textarea id="featurename" typeof="text" name="Features"  class="form-control features_list" placeholder="Add features and seperate with comma"></textarea>
                 </td>
                  <td class="text-center">
                    <button class="btn btn-danger remove"
                      type="button">Remove</button>
                    </td>
                  </tr>`);
                  
                }

            });
            // jQuery button click event to remove a row.
            $('#tbody').on('click', '.remove', function () {

                // Getting all the rows next to the row
                // containing the clicked button
                var child = $(this).closest('tr').nextAll();

                // Iterating across all the rows
                // obtained to change the index
                child.each(function () {

                    // Getting <tr> id.
                    var id = $(this).attr('id');

                    // Getting the <p> inside the .row-index class.
                    var idx = $(this).children('.row-index').children('p');

                    // Gets the row number from <tr> id.
                    var dig = parseInt(id.substring(1));

                    // Modifying row index.
                    idx.html(`Row ${dig - 1}`);

                    // Modifying row id.
                    $(this).attr('id', `R${dig - 1}`);
                });

                // Removing the current row.
                $(this).closest('tr').remove();

                // Decreasing total number of rows by 1.
                rowIdx--;
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/admin/js/pages/PricingPackages.js"></script>
}

Hospital/Views/PricingPacks/Delete.cshtml
@model Hospital.Models.PricingPacks

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PricingPack</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlanName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlanName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingPeroid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingPeroid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hospital/Views/PricingPacks/Details.cshtml
@model Hospital.Models.PricingPacks

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Details</h2>

<div class="content">
    <div class="row">
        <div class="col-sm-4 col-3">
            <h4 class="page-title">Pricing Packages</h4>
        </div>

    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-border table-striped custom-table datatable mb-0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.PlanName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.BillingPeroid)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Amount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(model => model.PlanName)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.BillingPeroid)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Amount)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.CreatedDate)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
                                <a asp-action="Index">Back to List</a>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Hospital/Views/PricingPacks/Edit.cshtml
@model Hospital.Models.PricingPacks

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Edit</h2>

<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Pricing Packages</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <form asp-action="Edit">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <input type="hidden" asp-for="id" />
                        <div class="form-group">
                            <i class="fa fa-tasks" aria-hidden="true"></i>  <label asp-for="PlanName" class="control-label"></label>
                            <input type="text" required asp-for="PlanName" class="form-control" />
                            <span asp-validation-for="PlanName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <i class="fa fa-clock-o"></i> <label asp-for="BillingPeroid" class="control-label"></label>
                            <input type="text" required asp-for="BillingPeroid" class="form-control" />
                            <span asp-validation-for="BillingPeroid" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <div class="form-group">
                            <i class="fa fa-money" aria-hidden="true"></i>  <label asp-for="Amount" class="control-label"></label>
                            <input type="number" min="0" required asp-for="Amount" class="form-control" />
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <i class="fa fa-file-text" aria-hidden="true"></i>  <label asp-for="Description" class="control-label"></label>
                            <textarea rows="+5" type="text" required asp-for="Description" class="form-control" > </textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    @*<div class="form-group">
            <label asp-for="CreateDate" class="control-label"></label>
            <input type="date" required asp-for="CreateDate" class="form-control" />
            <span asp-validation-for="CreateDate" class="text-danger"></span>
        </div>*@
                </div>
                    <div class="m-t-20 text-center">
                        <button class="btn btn-success submit-btn">Save</button>
                    </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Hospital/Views/PricingPacks/EditPackage.cshtml
@model Hospital.Models.PricingPacks

@{
    ViewData["Title"] = "EditPackage";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<div class="content">
    <div class="row">
        <div class="col-lg-12 offset-lg-12">
            <h4 class="page-title">Edit Packages</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 offset-lg-12">
            <form asp-action="Update" asp-controller="PricingPacks" id="updatePackageForm">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <input type="hidden" asp-for="id" />
                            <input type="hidden" asp-for="IsDeleted" />
                            <input type="hidden" asp-for="CreatedDate" />
                            <input type="hidden" asp-for="IsActive" value="false" />
                            <i class="fa fa-file-text-o" aria-hidden="true"></i> <label asp-for="PlanName" class="control-label"></label>
                            <input type="text" asp-for="PlanName" class="form-control" />
                            <span asp-validation-for="PlanName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label asp-for="PlanType" class="control-label"></label>
                            <i class="fa fa-asterisk" aria-hidden="true"></i>   <input type="radio" asp-for="PlanType" name="PlanType" value="@PlanType.Free" class="planType" /> Free
                            <input type="radio" asp-for="PlanType" name="PlanType" value="@PlanType.Paid" class="planType" /> Paid
                            <span asp-validation-for="PlanType" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <i class="fa fa-calendar" aria-hidden="true"></i>  <label asp-for="BillingPeroid" class="control-label"></label>
                            <input type="text" asp-for="BillingPeroid" class="form-control" />
                            <span asp-validation-for="BillingPeroid" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <i class="fa fa-money" aria-hidden="true"></i>   <label asp-for="Amount" class="control-label"></label>
                            $<input type="number" min="0" asp-for="Amount" class="form-control" />
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <i class="fa fa-file" aria-hidden="true"></i>  <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>


                <div class="m-t-20 text-center">
                    <button type="submit" class="btn btn-success submit-btn">Create Packages</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/admin/js/pages/PricingPackages.js"></script>
}

Hospital/Views/PricingPacks/Index.cshtml
@model IEnumerable<Hospital.Models.PricingPacks>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<style>
    table.dataTable thead th, table.dataTable thead td {
        white-space: nowrap;
    }
    table.dataTable tbody th, table.dataTable tbody td {
        vertical-align: middle;
    }
</style>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin/index">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pricing Packs</li>
    </ol>
</nav>
<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Pricing Packages</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <a asp-action="Create" class="btn btn btn-success btn-rounded float-right p_package_btn">Create New</a>
            <div class="table-responsive">
                <table class="table table-border" id="Tbl-PricingPackage">
                    <thead>
                        <tr>
                            <th><i class="fa fa-id-card" aria-hidden="true"></i>S.No</th>
                            <th>
                                <i class="fa fa-life-ring" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.PlanName)
                            </th>
                            <th>
                                <i class="fa fa-file" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                <i class="fa fa-calendar" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.BillingPeroid)
                            </th>
                            <th>
                                <i class="fa fa-money" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Amount)
                            </th>
                            <th>
                                <i class="fa fa-list-alt" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Features)
                            </th>
                            <th>
                                <i class="fa fa-asterisk" aria-hidden="true"></i> @Html.DisplayNameFor(model => model.PlanType)
                            </th>
                            <th>
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th>  <i class="fa fa-calendar" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.CreatedDate)</th>
                            <th>  <i class="fa fa-calendar" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.ModifiedDate)</th>
                            <th><i class="fa fa-gavel" aria-hidden="true"></i> Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script src="~/admin/js/pages/PricingPackages.js"></script>
}