Hospital/Models/AccountViewModels/ResetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models.AccountViewModels
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }
}

Hospital/Models/CommonModels/ChatViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models.CommonModels
{
    public class ChatViewModel
    {
        public partial class ReciverMessage
        {
            public string FirstName { get; set; }
            public string Message { get; set; }
            public DateTime MessageDate { get; set; }
            public string SelectedId { get; set; }
        }
        public partial class SenderMessage
        {
            public string FirstName { get; set; }
            public string Message { get; set; }
            public DateTime MessageDate { get; set; }
            public string SelectedId { get; set; }
        }
        public IEnumerable<ReciverMessage> ReciverMessages { get; set; }
        public IEnumerable<SenderMessage> SenderMessages { get; set; }
    }
}

Hospital/Controllers/SubAdmin/NursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital.Models;
using Hospital.Models.SubAdmin;
using Hospital.CollectionViewModel;
using Microsoft.AspNetCore.Authorization;
using Hospital.Models.CommonModels;
using static Hospital.Models.CommonModels.ChatViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Hospital.ViewModels;
using Hospital.Models.AccountViewModels;

namespace Hospital.Controllers.SubAdmin
{
    [Authorize(Roles = "Nurse")]
    public class NursesController : Controller
    {
        private readonly HMSContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public NursesController(HMSContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {

            var nurs = _context.Users.Where(c => c.Id == _userManager.GetUserId(HttpContext.User)).FirstOrDefault();
            ViewBag.nursLists = _context.Users.Where(c => c.HospitalID == nurs.HospitalID && c.Role == "Nurse").ToList();
            ViewBag.docLists = _context.Users.Where(c => c.HospitalID == nurs.HospitalID && c.Role == "Doctor").ToList();
            var date = DateTime.Now.Date;
            var model = new CollectionOfAll
            {
                //Departments = _context.Departments.Where(c => c.HospitalID == nurs.HospitalID).ToList(),
                //Doctors = _context.Users.ToList(),
                Patients = _context.Patients.Where(c => c.HospitalID == nurs.HospitalID).ToList(),
                Appointments = _context.Appointments.Where(c => c.HospitalID == nurs.HospitalID).ToList(),
                Department = _context.Departments.Where(c => c.HospitalID == nurs.HospitalID).ToList(),
                Schedules = _context.Schedules.Where(c => c.HospitalID == nurs.HospitalID).ToList(),
                Allotments = _context.Allotments.ToList(),
                //Nurses=_context.Users.ToList()

               
            };
            return View(model);
        }


        // GET: Nurses
        public async Task<IActionResult> NurseList()
        {
            var nurs = _context.Users.Where(c => c.Id == _userManager.GetUserId(HttpContext.User)).FirstOrDefault();
            ViewBag.ListOfNurses = _context.Users.Where(c => c.HospitalID == nurs.HospitalID && c.Role == "Nurse").ToList();
            //var hMSContext = _context.Nurses.Include(n => n.ApplicationUser);
            //return View(await hMSContext.ToListAsync());
            return View();
        }

        // GET: Nurses/Details/5
        public async Task<IActionResult> NurseDetails(string id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.Users.FirstOrDefaultAsync(m => m.Id == id);
            if (data == null)
            {
                return NotFound();
            }

            ViewBag.nurseDetail = data;

            return View();
        }

        // GET: Nurses/Create
        //public IActionResult AddNurse()
        //{
        //    ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
        //    return View();
        //}

        // POST: Nurses/Create
        
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> AddNurse([Bind("Id,ApplicationUserId,FullName,EmailAddress,Address,MobileNo,Gender,BloodGroup,DateOfBirth,Status")] Nurse nurse)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(nurse);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(NurseList));
        //    }
        //    ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", nurse.ApplicationUserId);
        //    return View(nurse);
        //}

        // GET: Nurses/Edit/5
        //public async Task<IActionResult> EditNurse(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var nurse = await _context.Nurses.FindAsync(id);
        //    if (nurse == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", nurse.ApplicationUserId);
        //    return View(nurse);
        //}

        // POST: Nurses/Edit/5
        
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> EditNurse(int id, [Bind("Id,ApplicationUserId,FullName,EmailAddress,Address,MobileNo,Gender,BloodGroup,DateOfBirth,Status")] Nurse nurse)
        //{
        //    if (id != nurse.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(nurse);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!NurseExists(nurse.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(NurseList));
        //    }
        //    ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", nurse.ApplicationUserId);
        //    return View(nurse);
        //}

        //Nurse Delete 
        public async Task<IActionResult> NurseDelete(string id)
        {
            var data = await _context.Users.FindAsync(id);
            if (data == null)
            {
                return NotFound();

            }
            _context.Users.Remove(data);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(NurseList));
        }

        private bool NurseExists(int id)
        {
            return _context.Nurses.Any(e => e.Id == id);
        }

        //Patient List
        // GET: Patients
        public async Task<IActionResult> PatientList()
        {
            var nurs = _context.Users.Where(c => c.Id == _userManager.GetUserId(HttpContext.User)).FirstOrDefault();
            return View(await _context.Patients.Where(c => c.HospitalID == nurs.HospitalID).ToListAsync());
        }
        // GET: Patients/Details/5

        public async Task<IActionResult> PatientDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients
                .FirstOrDefaultAsync(m => m.PatientID == id);
            if (patients == null)
            {
                return NotFound();
            }

            return View(patients);
        }

        public async Task<IActionResult> PatientDelete(int id)
        {
            var book = await _context.Patients.FindAsync(id);
            if (book == null)
            {
                return NotFound();

            }
            _context.Patients.Remove(book);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(PatientList));
        }


        private bool PatientsExists(int id)
        {
            return _context.Patients.Any(e => e.PatientID == id);
        }

        //Room Allotment
        // GET: Allotments
        public async Task<IActionResult> AllotmentList()
        {
            return View(await _context.Allotments.ToListAsync());
        }

        // GET: Allotments/Details/5
        public async Task<IActionResult> AllotmentDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allotment = await _context.Allotments
                .FirstOrDefaultAsync(m => m.AllotmentId == id);
            if (allotment == null)
            {
                return NotFound();
            }

            return View(allotment);
        }

        // GET: Allotments/Create
        public IActionResult AddAllotment()
        {
            return View();
        }

        // POST: Allotments/Create
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAllotment([Bind("AllotmentId,Room,RoomType,PatientName,AllotmentDate,DischargeDate,DoctorName,Status")] Allotment allotment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(allotment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(AllotmentList));
            }
            return View(allotment);
        }

        // GET: Allotments/Edit/5
        public async Task<IActionResult> EditAllotment(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allotment = await _context.Allotments.FindAsync(id);
            if (allotment == null)
            {
                return NotFound();
            }
            return View(allotment);
        }

        

        public async Task<IActionResult> AllotmentDelete(int id)
        {
            var book = await _context.Allotments.FindAsync(id);
            if (book == null)
            {
                return NotFound();

            }
            _context.Allotments.Remove(book);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(AllotmentList));
        }
        private bool AllotmentExists(int id)
        {
            return _context.Allotments.Any(e => e.AllotmentId == id);
        }

Hospital/Views/Nurses/AllotmentDetails.cshtml
@model Hospital.Models.SubAdmin.Allotment

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_NursesLayout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Room Allotments Details</h4>
        </div>
    </div>
    <div class="row">
        <!-- Widget Item -->
        <div class="col-md-12">
            <div class="widget-area-2 proclinic-box-shadow">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <td> <h4> @Html.DisplayNameFor(model => model.Room)</h4>  </td>
                                <td> @Html.DisplayFor(model => model.Room)</td>
                            </tr>
                            <tr>
                                <td> <h4>  @Html.DisplayNameFor(model => model.RoomType)</h4> </td>
                                <td>  @Html.DisplayFor(model => model.RoomType) </td>
                            </tr>
                            <tr>
                                <td> <h4>   @Html.DisplayNameFor(model => model.PatientName) </h4> </td>
                                <td>   @Html.DisplayFor(model => model.PatientName)</td>
                            </tr>
                            <tr>
                                <td><h4>   @Html.DisplayNameFor(model => model.AllotmentDate) </h4> </td>
                                <td>  @Html.DisplayFor(model => model.AllotmentDate) </td>
                            </tr>
                            <tr>
                                <td><h4>  @Html.DisplayNameFor(model => model.DischargeDate) </h4> </td>
                                <td>   @Html.DisplayFor(model => model.DischargeDate) </td>
                            </tr>
                            <tr>
                                <td> <h4>  @Html.DisplayNameFor(model => model.DoctorName) </h4> </td>
                                <td>  @Html.DisplayFor(model => model.DoctorName)</td>
                            </tr>
                            <tr>
                                <td><h4>   @Html.DisplayNameFor(model => model.Status)</h4> </td>
                                <td> @Html.DisplayFor(model => model.Status) </td>
                            </tr>
                        </tbody>
                    </table>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination export-pagination">
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-download "></span> csv</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-printer"></span> print</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-file "></span> PDF</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-align-justify "></span> Excel</a>
                            </li>
                        </ul>
                    </nav>
                    <div>
                        <a asp-action="EditAllotment" asp-route-id="@Model.AllotmentId" class="btn btn-success mb-3"><i class="fa fa-pencil m-r-5"></i>Edit Allotment</a>
                        <a class="btn btn-success mb-3" asp-controller="Nurses" asp-action="AllotmentDelete" asp-route-id="@Model.AllotmentId" onclick="return confirm('Are you sure want to delete this room allotment ?')"><i class="fa fa-trash-o m-r-5"></i> Delete Allotment</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Hospital/Views/Nurses/DepartmentDetails.cshtml
@model Hospital.Models.SubAdmin.Department

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_NursesLayout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Department Details</h4>
        </div>
    </div>
    <div class="row">
        <!-- Widget Item -->
        <div class="col-md-12">
            <div class="widget-area-2 proclinic-box-shadow">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <td><h4>@Html.DisplayNameFor(model => model.DepartmentName)</h4></td>
                                <td> @Html.DisplayFor(model => model.DepartmentName)</td>
                            </tr>
                            <tr>
                                <td><h4> @Html.DisplayNameFor(model => model.Description)</h4></td>
                                <td> @Html.DisplayFor(model => model.Description)</td>
                            </tr>
                            <tr>
                                <td><h4> @Html.DisplayNameFor(model => model.DepartmentStatus)</h4></td>
                                <td> @Html.DisplayFor(model => model.DepartmentStatus)</td>
                            </tr>
                        </tbody>
                    </table>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination export-pagination">
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-download "></span> csv</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-printer"></span> print</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-file "></span> PDF</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-align-justify "></span> Excel</a>
                            </li>
                        </ul>
                    </nav>
                    <div>
                        @*<a asp-action="EditDepartment" asp-route-id="@Model.DepartmentID" class="btn btn-success mb-3"><i class="fa fa-pencil m-r-5"></i>Edit Department</a>*@

                        <a class="btn btn-success mb-3" asp-controller="Nurses" asp-action="DepartmentDelete" asp-route-id="@Model.DepartmentID" onclick="return confirm('Are you sure want to delete this Department?')"><i class="fa fa-trash-o m-r-5"></i> Delete Department</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

            

Hospital/Views/Nurses/DepartmentList.cshtml
@model IEnumerable<Hospital.Models.SubAdmin.Department>

@{
    ViewData["Title"] = "DepartmentList";
    Layout = "~/Views/Shared/_NursesLayout.cshtml";
}

<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h2 class="page-title page-title_main">Department</h2>
        </div>
        
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="table-responsive">
                <table class="table table-border table-striped custom-table datatable mb-0">
                    <thead>
                        <tr>
                            <th>
                                <i class="fa fa-building-o" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.DepartmentName)
                            </th>
                            <th>
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                              <i class="fa fa-toggle-on"></i>  @Html.DisplayNameFor(model => model.DepartmentStatus)
                            </th>
                            <th class="text-center">
                                <i class="fa fa-gavel"></i> Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.DepartmentName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @if (item.DepartmentStatus == "Active")
                                {
                                    <span class="custom-badge status-green">
                                        @Html.DisplayFor(modelItem => item.DepartmentStatus)
                                    </span>
                                }
                                else if (item.DepartmentStatus == "IsActive")
                                {
                                    <span class="custom-badge status-red">
                                        @Html.DisplayFor(modelItem => item.DepartmentStatus)
                                    </span>
                                }
                                else
                                {

                                }
                            </td>
                            <td class="text-center">
                                @*<a asp-action="EditDepartment" asp-route-id="@item.DepartmentID"><i class="fa fa-pencil-square-o" style="font-size: 19px"></i></a> |*@
                                <a asp-action="DepartmentDetails" asp-route-id="@item.DepartmentID"><i class="fa fa-info-circle m-r-5" style="font-size: 19px; color: lightblue"></i></a> 
                                @*<a asp-controller="Nurses" asp-action="DepartmentDelete" asp-route-id="@item.DepartmentID" onclick="return confirm('Are you sure want to delete this Department?')"><i class="fa fa-trash-o m-r-5" style="font-size: 19px; color: red"></i></a>*@
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
                </div>
</div>
</div>
</div>

Hospital/Views/Nurses/NurseDetails.cshtml
@model Hospital.Models.SubAdmin.Nurse

@{
    ViewData["Title"] = "NurseDetails";
    Layout = "~/Views/Shared/_NursesLayout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Nurse Details</h4>
        </div>
    </div>
    <div class="row">
        <!-- Widget Item -->
        <div class="col-md-12">
            <div class="widget-area-2 proclinic-box-shadow">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <td>
                                    <h4>  @Html.DisplayNameFor(model => model.FullName)</h4>
                                </td>
                                <td>  @ViewBag.nurseDetail.FirstName @ViewBag.nurseDetail.LastName</td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>  @Html.DisplayNameFor(model => model.EmailAddress) </h4>
                                </td>
                                <td>   @ViewBag.nurseDetail.Email</td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>@Html.DisplayNameFor(model => model.Street)</h4>
                                </td>
                                <td>
                                    @ViewBag.nurseDetail.Street
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <h4> @Html.DisplayNameFor(model => model.City)</h4>
                                </td>
                                <td>
                                    @ViewBag.nurseDetail.City
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>@Html.DisplayNameFor(model => model.State)</h4>
                                </td>
                                <td>
                                    @ViewBag.nurseDetail.State
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>@Html.DisplayNameFor(model => model.ZipCode)</h4>
                                </td>
                                <td>
                                    @ViewBag.nurseDetail.ZipCode
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>@Html.DisplayNameFor(model => model.Country)</h4>
                                </td>
                                <td>
                                    @ViewBag.nurseDetail.Country
                                </td>
                            </tr>
                            <tr>
                            <tr>
                                <td>
                                    <h4> @Html.DisplayNameFor(model => model.MobileNo) </h4>
                                </td>
                                <td>  @ViewBag.nurseDetail.PhoneNumber</td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>   @Html.DisplayNameFor(model => model.Gender)</h4>
                                </td>
                                <td>   @ViewBag.nurseDetail.Gender </td>
                            </tr>
                            <tr>
                                <td>
                                    <h4> @Html.DisplayNameFor(model => model.BloodGroup) </h4>
                                </td>
                                <td> @ViewBag.nurseDetail.BloodGroup</td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>   @Html.DisplayNameFor(model => model.DateOfBirth) </h4>
                                </td>
                                <td>   @ViewBag.nurseDetail.DOB</td>
                            </tr>
                            <tr>
                                <td>
                                    <h4>  @Html.DisplayNameFor(model => model.Status)</h4>
                                </td>
                                <td>  @ViewBag.nurseDetail.Availiablity </td>
                            </tr>
                        </tbody>
                    </table>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination export-pagination">
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-download "></span> csv</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-printer"></span> print</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-file "></span> PDF</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><span class="fa fa-align-justify"></span> Excel</a>
                            </li>
                        </ul>
                    </nav>
                    <div>
                        @*<a asp-action="EditNurse" asp-route-id="@Model.Id" class="btn btn-success mb-3"><i class="fa fa-pencil m-r-5"></i> Edit Nurse</a>*@

                        <a class="btn btn-danger mb-3" asp-controller="Nurses" asp-action="NurseDelete" asp-route-id="@ViewBag.nurseDetail.Id" onclick="return confirm('Are you sure want to delete this nurse ?')"><i class="fa fa-trash-o m-r-5"></i> Delete Nurse</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Hospital/Views/Nurses/ResetPassword.cshtml
@model Hospital.Models.AccountViewModels.changePassViewModel
@{
    ViewData["Title"] = "ResetPassword";
    Layout = "~/Views/Shared/_NursesLayout.cshtml";
}

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h4 class="page-title page-title_main">Reset Password</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <form asp-action="ResetPassword" asp-controller="Nurses" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <div class="form-group">
                                <i class="fa fa-key" aria-hidden="true"></i>
                                <label asp-for="Password" class="control-label">New password</label>
                                <input type="password" asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <div class="form-group">
                                <i class="fa fa-lock" aria-hidden="true"></i> <label asp-for="ConfirmPassword" class="control-label">Confirm new password</label>
                                <input type="password" asp-for="ConfirmPassword" class="form-control" />
                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="m-t-20 text-center">
                        <button class="btn btn-success submit-btn">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>