Hospital/Models/AccountViewModels/ResetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models.AccountViewModels
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }
}

Hospital/Models/CommonModels/ChatViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models.CommonModels
{
    public class ChatViewModel
    {
        public partial class ReciverMessage
        {
            public string FirstName { get; set; }
            public string Message { get; set; }
            public DateTime MessageDate { get; set; }
            public string SelectedId { get; set; }
        }
        public partial class SenderMessage
        {
            public string FirstName { get; set; }
            public string Message { get; set; }
            public DateTime MessageDate { get; set; }
            public string SelectedId { get; set; }
        }
        public IEnumerable<ReciverMessage> ReciverMessages { get; set; }
        public IEnumerable<SenderMessage> SenderMessages { get; set; }
    }
}

Hospital/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models
{
    public class Payment
    {
        [Key]
        public int id { get; set; }
        [Required]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Patient ID")]
        public string Patient_ID { get; set; }
        [Required]
        [Display(Name = "Patient Name")]
        public string Patient_Name { get; set; }
        [Display(Name = "Status")]
        public string Status { get; set; }
        [Required]
        [Display(Name = "Payment Detail")]
        public string PaymentDetail { get; set; }
        [Required]
        [Display(Name = "Amount")]
        public string Amount { get; set; }
        [Display(Name = "Deposit Amount")]
        public string Deposit_Amount { get; set; }
        [Display(Name = "Pending Amount")]
        public string Pending_Amount { get; set; }
        [Display(Name = "Created Date")]
        public string CreatedDate { get; set; }
        [Display(Name = "Deposit Date")]
        public string Deposit_Date { get; set; }
        public string HospitalID { get; set; }
        [NotMapped]
        public string Payment_Complete { get; set; }
    }
}

Hospital/Controllers/SubAdmin/HospitalAdminController.cs
using Hospital.CollectionViewModel;
using Hospital.Models;
using Hospital.Models.SubAdmin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Hospital.Helper;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Hospital.Services;
using Hospital.Models.AccountViewModels;
using Microsoft.AspNetCore.Identity.UI.Services;
using Hospital.DBServices.SuperAdmin;
using Hospital.Models.CommonModels;
using Hospital.DBServices.HospitalAdmin;
using Microsoft.AspNetCore.Http;
using static Hospital.Models.CommonModels.ChatViewModel;
using Hospital.ViewModels;
using Newtonsoft.Json.Serialization;
using Hospital.Models.SuperAdminModels;
using AutoMapper;

namespace Hospital.Controllers.SubAdmin
{
    [Authorize(Roles = "HospitalAdmin,StaffMember")]
    public class HospitalAdminController : Controller
    {
        private readonly HMSContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<HomeController> _logger;
        private readonly IEmailSender _emailSender;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ISuperAdmin _superAdmin;
        private readonly IHospitalAdmin _hospitalAdmin;
        private readonly IMapper _mapper;
        public HospitalAdminController(HMSContext context, IHospitalAdmin hospitalAdmin, ISuperAdmin superAdmin, UserManager<ApplicationUser> userManager, ILogger<HomeController> logger, IEmailSender emailSender, SignInManager<ApplicationUser> signInManager, IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
            _emailSender = emailSender;
            _signInManager = signInManager;
            _superAdmin = superAdmin;
            _hospitalAdmin = hospitalAdmin;
            _mapper = mapper;
        }
        public IActionResult Index(int findId)
        {
            string date = DateTime.Now.ToString("dd-MM-yyyy");
            ViewBag.NumberOfDialyPatients = _context.Patients.Where(c => c.CreatedDate == date).ToList();
            ViewBag.btnValue = findId;
            if (findId == 1)
            {
                ViewBag.NumberOfDialyPatients = _context.Patients.Where(c => c.CreatedDate == date && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            }
            else
            if (findId == 2)
            {
                ViewBag.NumberOfDialyPatients = _context.Appointments.Where(c => c.CreatedDate == date && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            }

            ViewBag.TotalDoctor = _context.Users.Where(c => c.Role == "Doctor" && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            ViewBag.TotalNumberOfNurse = _context.Users.Where(c => c.Role == "Nurse" && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            ViewBag.TotalPatients = _context.Users.Where(c => c.Role == "Patients" && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
           // ViewBag.TotalPatients = _context.Patients.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
          //  ViewBag.Patients = _context.Patients.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            ViewBag.Department = _context.Departments.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            ViewBag.Appointments = _context.Appointments.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            ViewBag.Schedules = _context.Schedules.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
            ViewBag.Allotments = _context.Allotments.ToList();
            var model = new CollectionOfAll
            {

                Doctors = _context.Doctor.ToList(),
                Patients = _context.Patients.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList(),
                Appointments = _context.Appointments.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList(),
                Department = _context.Departments.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList(),
                Schedules = _context.Schedules.Where(c => c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList(),
                Allotments = _context.Allotments.ToList(),
                Nurses = _context.Nurses.ToList()

            };
            return View(model);
        }

        //public IActionResult DialyRecords(int findId)
        //{
        //    string date = DateTime.Now.ToString("dd-MM-yyyy");
        //    if (findId == 1)
        //    {
        //        ViewBag.NumberOfDialyPatients = _context.Patients.Where(c => c.CreatedDate == date && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
        //    }else
        //    if (findId == 2)
        //    {
        //        ViewBag.NumberOfDialyPatients = _context.Appointments.Where(c => c.CreatedDate == date && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToList();
        //    }

        //    return RedirectToAction(nameof(Index));
        //}

        //GET: Doctors
        public async Task<IActionResult> DoctorList()
        {
            //var data = _context.Users.Where(c => c.Role == "Doctor").ToList();
            //ViewBag.doclist = data;

            return View(await _context.Users.Where(c => c.Role == "Doctor" && c.HospitalID == _userManager.GetUserId(HttpContext.User)).ToListAsync());
        }

        //ss GET: Doctors/Details/5
        public async Task<IActionResult> DoctorDetails(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }



        // GET: Doctors/Create
        public IActionResult AddDoctor()
        {
            return View();
        }



        // POST: Doctors/Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DoctorList([Bind("DoctorId,DoctorName,DOB,Age,Specialization,Experience,Email,PhoneNo,FaxNo,Street,City,State,ZipCode,Country,DoctorDetails,Password,Availiablity")] Doctor doctor)
        //{

        //    var docter = _context.Doctor.Where(c => c.Email == doctor.Email).ToList();

        //    var patient = _context.Patients.Where(c => c.Email == doctor.Email).ToList();

        //    var nurse = _context.Nurses.Where(c => c.EmailAddress == doctor.Email).ToList();

        //    if(patient.Count != 0)
        //    {
        //        Console.WriteLine("Email Already used in Patient.");
        //    }

        //    if (nurse.Count != 0)
        //    {
        //        Console.WriteLine("Email Already used in Nurses.");
        //    }

        //    if (docter.Count == 0 && patient.Count == 0 && nurse.Count == 0)
        //    {

        //        //var roleDocter = _context.Roles.Where(c => c.Name == "Doctor").FirstOrDefault();

        //        if (ModelState.IsValid)
        //        {
        //            var pass = EncryptDecrypt.Encode(doctor.Password);
        //            doctor.Password = pass;
        //            //var docterid = EncryptDecrypt.Encode(doctor.DoctorId);



        //            _context.Add(doctor);
        //            await _context.SaveChangesAsync();


        //            return RedirectToAction(nameof(DoctorList));
        //        }
        //    }
        //    //Console.WriteLine("Email already exist......");
        //    return View("AddDoctor");

        //}

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<dynamic> AddDoctor(DoctorViewModel model)
        {

            model.Email = model.Email;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new ApplicationUser { UserName = model.Email, Email = model.Email, FirstName = model.DoctorName, DOB = model.DOB, Age = model.Age, Availiablity = model.Availiablity, City = model.City, Country = model.Country, DoctorDetails = model.DoctorDetails, Experience = model.Experience, FaxNo = model.FaxNo, Specialization = model.Specialization, State = model.State, Street = model.Street, ZipCode = model.ZipCode, PhoneNumber = model.PhoneNo, Role = "Doctor", HospitalID = _userManager.GetUserId(HttpContext.User), CreatedDate = DateTime.Now.ToString("dd-MM-yyyy") };
            var result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {

                // Add a user to the default role, or any role you prefer here
                await _userManager.AddToRoleAsync(user, "Doctor");
                //await _userManager.AddToRoleAsync(user, model.UserRole.ToString());

                //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                //var callbackUrl = Url.EmailConfirmationLink(user.Id, code, Request.Scheme);
                //await _emailSender.SendEmailConfirmationAsync(model.Email, callbackUrl);

                //await _signInManager.SignInAsync(user, isPersistent: false);
                // _logger.LogInformation("User created a new account with password.");
                ViewBag.isSuccess = true;
                return View(model);

                //return RedirectToAction(nameof(DoctorList));

            }

Hospital/Views/HospitalAdmin/AllotmentList.cshtml
@model IEnumerable<Hospital.Models.SubAdmin.Allotment>

@{
    ViewData["Title"] = "AllotmentList";
    Layout = "~/Views/Shared/_HospitalAdminLayout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/HospitalAdmin/index" class="main_page">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Allotment List</li>

    </ol>
</nav>
<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h2 class="page-title page-title_main">Allotments Lists</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="table-responsive">
                <table class="table table-border table-striped custom-table datatable mb-0">
                    <thead>
                        <tr>
                            <th>
                                <i class="fa fa-bed" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Room)
                            </th>
                            <th>
                                <i class="fa fa-medium" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.RoomType)
                            </th>
                            <th>
                                <i class="fa fa-wheelchair" aria-hidden="true"></i>  @Html.DisplayNameFor(model => model.PatientName)
                            </th>
                            <th>
                                <i class="fa fa-calendar" aria-hidden="true"></i>    @Html.DisplayNameFor(model => model.AllotmentDate)
                            </th>
                            <th>
                                <i class="fa fa-calendar" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.DischargeDate)
                            </th>
                            <th>
                                <i class="fa fa-user-md"></i>   @Html.DisplayNameFor(model => model.DoctorName)
                            </th>
                            <th>
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Status)
                            </th>
                            <th class="text-center">
                                <i class="fa fa-gavel"></i>  Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Room)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RoomType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PatientName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AllotmentDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DischargeDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DoctorName)
                                </td>
                                <td>
                                    @if (item.Status == "Available")
                                    {
                                        <span class="custom-badge status-green">
                                            @Html.DisplayFor(modelItem => item.Status)
                                        </span>
                                    }
                                    else if (item.Status == "Not Discharge")
                                    {
                                        <span class="custom-badge status-red">
                                            @Html.DisplayFor(modelItem => item.Status)
                                        </span>
                                    }
                                    else if (item.Status == "Not Alloted")
                                    {
                                        <span class="custom-badge status-blue">
                                            @Html.DisplayFor(modelItem => item.Status)
                                        </span>
                                    }

                                </td>

                                <td class="text-center">
                                    <a asp-action="AllotmentDetails" asp-route-id="@item.AllotmentId"><i class="fa fa-info-circle m-r-5" style="font-size: 19px; color: lightblue"></i></a> |
                                    <a asp-controller="HospitalAdmin" asp-action="AllotmentDelete" asp-route-id="@item.AllotmentId" onclick="return confirm('Are you sure want to delete this Room Allotment?')"><i class="fa fa-trash-o m-r-5" style="font-size: 19px; color: red"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Hospital/Views/HospitalAdmin/AppointmentDetails.cshtml
@model Hospital.Models.SubAdmin.Appointments

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_HospitalAdminLayout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/HospitalAdmin/index" class="main_page">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Appointment Details</li>

    </ol>
</nav>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h4 class="page-title page-title_main">Appointment Details</h4>
            </div>
        </div>
        <div class="row">
            <!-- Widget Item -->
            <div class="col-md-12">
                <div class="widget-area-2 proclinic-box-shadow">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <td><h4>@Html.DisplayNameFor(model => model.PatientId)</h4></td>
                                    <td> @Html.DisplayFor(model => model.PatientId)</td>
                                </tr>
                                <tr>
                                    <td><h4>  @Html.DisplayNameFor(model => model.DoctorName)</h4></td>
                                    <td> @Html.DisplayFor(model => model.DoctorName)</td>
                                </tr>
                                <tr>
                                    <td><h4> @Html.DisplayNameFor(model => model.Department)</h4></td>
                                    <td> @Html.DisplayFor(model => model.Department)</td>
                                </tr>
                                <tr>
                                    <td><h4> @Html.DisplayNameFor(model => model.TokenNumber)</h4></td>
                                    <td> @Html.DisplayFor(model => model.TokenNumber)</td>
                                </tr>
                                <tr>
                                    <td><h4> @Html.DisplayNameFor(model => model.Problem)</h4></td>
                                    <td>  @Html.DisplayFor(model => model.Problem)</td>
                                </tr>
                                <tr>
                                    <td><h4> @Html.DisplayNameFor(model => model.AppointmentDate)</h4></td>
                                    <td> @Html.DisplayFor(model => model.AppointmentDate)</td>
                                </tr>
                                <tr>
                                    <td>
                                        <h4>    @Html.DisplayNameFor(model => model.TimeSlot)</h4>
                                    </td>
                                    <td> @Html.DisplayFor(model => model.TimeSlot)</td>
                                </tr>
                                <tr>
                                    <td><h4>@Html.DisplayNameFor(model => model.AppointmentStatus)</h4></td>
                                    <td> @Html.DisplayFor(model => model.AppointmentStatus)</td>
                                </tr>

                            </tbody>
                        </table>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination export-pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#"><span class="fa fa-download "></span> csv</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#"><span class="fa fa-printer"></span> print</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#"><span class="fa fa-file "></span> PDF</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#"><span class="fa fa-align-justify "></span> Excel</a>
                                </li>
                            </ul>
                        </nav>
                        <div>
                            <a asp-action="EditAppointment" asp-route-id="@Model.AppointmentId" class="btn btn-success mb-3"><i class="fa fa-pencil m-r-5"></i>Edit Appointment</a>

                            <a class="btn btn-danger mb-3" asp-controller="HospitalAdmin" asp-action="AppointmentDelete" asp-route-id="@Model.AppointmentId" onclick="return confirm('Are you sure want to delete this Appointment ?')"><i class="fa fa-trash-o m-r-5"></i> Delete Appointment</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Hospital/Views/HospitalAdmin/Birth_Report_Detail.cshtml
@*@model Hospital.Models.SubAdmin.Nurse*@
@model Hospital.Models.SubAdmin.NurseViewModel

@{
    ViewData["Title"] = "Birth Report Details";
    Layout = "~/Views/Shared/_HospitalAdminLayout.cshtml";
}
@section scripts{
    <script src="~/assets/js/main.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
}
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
<link rel="stylesheet" href="~/assets/css/form_wizard_css.css" />
<style>
    .btn.btn-danger.active:hover, .open > .btn.btn-danger.dropdown-toggle, .open > .btn.btn-danger.dropdown-toggle:focus, .open > .btn.btn-danger.dropdown-toggle:hover {
        background-color: #ea236d!important;
        color: #ea236d!important;
    }
</style>
@Html.Raw(TempData["msg"])
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/HospitalAdmin/index" class="main_page">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Birth Report Details</li>

    </ol>
</nav>
<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h4 class="page-title page-title_main">Birth Report Details</h4>
        </div>
    </div>

    <div class="row" style="border: 1px solid #b7b7b7; margin: 0px; padding: 10px;">
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2  col-xl-2">
            <lable>Patient Id: <b> 001</b></lable>
        </div>
  
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3  col-xl-3">
            <lable>Title: <b> Mr.Ram</b></lable>
        </div>
   
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3  col-xl-3">
            <lable>Description:  <b> Patient condiditon is critical,undertaking patient consultations and physical examinations · organising workloads · performing surgical procedures</b></lable>
        </div>
    
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2  col-xl-2">
            <lable>Doctor Name: <b> Dr.Akhilesh</b></lable>
        </div>
   
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2  col-xl-2">
            <lable>Date:  <b>16-06-2021</b></lable>
        </div>
    </div>
</div>

Hospital/Views/HospitalAdmin/DepartmentList.cshtml
@model IEnumerable<Hospital.Models.SubAdmin.Department>

@{
    ViewData["Title"] = "DepartmentList";
    Layout = "~/Views/Shared/_HospitalAdminLayout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/HospitalAdmin/index" class="main_page">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Department List</li>

    </ol>
</nav>
<div class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h2 class="page-title page-title_main">Department</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <a asp-action="AddDepartment" class="btn btn-success btn-rounded float-right add_appointment"><i class="fa fa-plus"></i> Add New Department  </a>
            <div class="table-responsive">
                <table class="table table-border table-striped custom-table datatable mb-0">
                    <thead>
                        <tr>
                            <th>
                                <i class="fa fa-building" aria-hidden="true"></i>    @Html.DisplayNameFor(model => model.DepartmentName)
                            </th>
                            <th>
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>   @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>    @Html.DisplayNameFor(model => model.DepartmentStatus)
                            </th>
                            <th class="text-center">
                                <i class="fa fa-gavel"></i>    Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DepartmentName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @if (item.DepartmentStatus == "Active")
                                    {
                                        <span class="custom-badge status-green">
                                            @Html.DisplayFor(modelItem => item.DepartmentStatus)
                                        </span>
                                    }
                                    else if (item.DepartmentStatus == "IsActive")
                                    {
                                        <span class="custom-badge status-red">
                                            @Html.DisplayFor(modelItem => item.DepartmentStatus)
                                        </span>
                                    }
                                    else
                                    {

                                    }
                                </td>
                                <td class="text-center">
                                    <a asp-action="EditDepartment" asp-route-id="@item.DepartmentID"><i class="fa fa-pencil-square-o" style="font-size: 19px"></i></a> |
                                    <a asp-action="DepartmentDetails" asp-route-id="@item.DepartmentID"><i class="fa fa-info-circle m-r-5" style="font-size: 19px; color: lightblue"></i></a> |
                                    <a asp-controller="HospitalAdmin" asp-action="DepartmentDelete" asp-route-id="@item.DepartmentID" onclick="return confirm('Are you sure want to delete this Department?')"><i class="fa fa-trash-o m-r-5" style="font-size: 19px; color:  #086972"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>